modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="crimsoncraft"
version="1.0.0"
displayName="CrimsonCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://gfhfhfhgh.net"
authors="WaryPug"

[[dependencies.crimsoncraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



